#define GADGET2
#define USE_POTENTIALS
#define USE_X_BAR
#define CENTER_ON_DISK_CENTROID
#define DENSITY_HISTOGRAMS
#define IOM_ANALYSIS
#define COMPUTE_VIRIAL_RATIO
#define COMPUTE_DISK_MOMENT_OF_INERTIA
#define COMPUTE_ANGULAR_MOMENTUM
#define ORIENT_WITH_INNER_ANGULAR_MOMENTUM
#define INNER_RADIUS 5.0
#define ROTATE_SYSTEM
#define OPENMP
#define G 4.492e-06
